# See https://pre-commit.com/ for usage and config
# Run hooks only on pyhack, others staged files will be commited without being checked
#exclude: '^(?!launch.py)'
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: pipenv run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pipenv run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: pipenv run flake8
    types: [python]
    exclude: setup.py

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: pipenv run pytest -v
    types: [python]
    pass_filenames: false
# pass_filenames est nécessaire à cause de launch.py qui importe pyhack

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: pipenv run pytest -v --cov # --cov-fail-under=0
    types: [python]
    pass_filenames: false
